site_name: ACRE
site_description: Manifesto for Figuration and Non-existence
site_author: ACRE-BUN
repo_url: https://github.com/ACRE-BUN/ACRE
repo_name: ACRE-BUN/ACRE

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - Home: index.md
  - Manifesto: 01_manifesto.md
  - Concepts:
      - Terms: 03_terms.md
      - Models: 04_models.md
  - Project:
      - Quickstart: 02_quickstart.md
      - FAQ: 05_faq.md
      - Changelog: 06_changelog.md
